version: '3.9'

services:
  postgres:
    container_name: masterskaya_veloservice_db
    image: postgres:17.2
    env_file:
      - docker.env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - onlineshopwebapp
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


  onlineshopwebapp:
    container_name: masterskaya_veloservice_web_app
    image: ${DOCKER_REGISTRY-}onlineshopwebapp
    env_file:
      - docker.env
    build:
      context: .
      dockerfile: OnlineShopWebApp/Dockerfile
    volumes:
      - images:/app/wwwroot/images
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - postgres
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
      
volumes:
  postgresql_data:
  data-protection-keys:
  images:  